### PR TITLE
I fix breadcrumbs and update product mvc and have tested, its works

### PR DESCRIPTION
**Pull request by wazzzar**
But I do some wrong right? 113 changed files. I changed only 3 files.

### CODE REVIEW

**Comment by prhost** [comment]
Upgrade your fork with upstream to resolve conflicts.

**Comment by wazzzar** [comment]
how can I do that, I have tried use git merge upstream/master , but git told merge: upstream/master - not something we can merge

**Comment by prhost** [comment]
check your remotes:
`git remotes -v`
If you not have added upstream, run:
`git remote add upstream https://github.com/copona/copona.git`

After execute:
`git checkout master`
`git merge upstream/master`

try it.

**Comment by wazzzar** [comment]
$ git remote -v
origin  https://github.com/wazzzar/copona.git (fetch)
origin  https://github.com/wazzzar/copona.git (push)

$ git remote add upstream https://github.com/copona/copona.git

$ git remote -v
origin  https://github.com/wazzzar/copona.git (fetch)
origin  https://github.com/wazzzar/copona.git (push)
upstream        https://github.com/copona/copona.git (fetch)
upstream        https://github.com/copona/copona.git (push)

$ git checkout master
Your branch is up-to-date with 'origin/master'.
Already on 'master'

$ git merge upstream/master
merge: upstream/master - not something we can merge

**Comment by prhost** [comment]
try exec `git fetch --all` before `git merge upstream/master`

**Comment by lucasjkr** [comment]
what is the purpose of $breadcrumb_html? 

I get this when visiting a product page:

`Notice: Undefined variable: breadcrumb_html in /home/copona/public_html/catalog/view/theme/default/template/product/product.tpl on line 8`

**Comment by arnisjuraga** [comment]
I think, there was left duplicated html for breadcrumbs. So one, the old one, must be removed?
@wazzzar can you review it?

**Comment by arnisjuraga** [comment]
Change have been made in separate  commits.

**Pull request closed without merging**
