### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by JJKalnins**

### CODE REVIEW

**Comment by prhost** [comment]
The `admin/view/template/customer/customer_form.tpl` file has broken formatting, I think your IDE did this. Can you leave what the old file was like?

**Comment by JJKalnins** [comment]
It doesn't show up so crazy in my files

**Comment by prhost** [comment]
See in your pull request, in the "Files changed" tab the file is almost everything to the left and there is a very large space in your middle.

**Comment by JJKalnins** [comment]
Fixed it

**Pull request merged**
