### PR TITLE
improvement to installation

### PR DESCRIPTION
**Pull request by lucasjkr**
This should do as follows:

1) Database creation integrates all migrations to date

2) If the server is apache and has mod_rewrite enabled, it creates the .htaccess file AND enables seo_url’s by default

### CODE REVIEW

**Comment by lucasjkr** [comment]
If anybody is testing with Nginx, would you please verify that .htaccess is NOT created and that SEO Url's are not turned on after installation?

Todo: change RewriteBase in the .htaccess file to match what's given in HTTPS_SERVER in the event that the store isn't hosted in the root directory of the site.

**Comment by ADDCreative** [comment]
I think you should only overwrite .htaccess if it does not already exist. As there could already be a file with settings in. I can see you check file_exists, but then only touch a file that doesn't exist.

Also need to remove the references to OpenCart.

**Comment by lucasjkr** [comment]
Good points. I will do both of those issues today...

**Comment by lucasjkr** [comment]
#117

**Pull request merged**
