### PR TITLE
fix for #122

### PR DESCRIPTION
**Pull request by lucasjkr**
We’re checking the output of phpinfo() rather than apache_get_modules()
to fix fatal error when PHP is installed as CGI rather than as module.

In this case, .htaccess file and seo_urls will only be enabled if the
server is Apache and mod_rewrite is found in the output of phpinfo()

### CODE REVIEW

**Comment by prhost** [comment]
Opencart only runs in apache?

**Comment by lucasjkr** [comment]
No, this relates to automatically enabling SEO URL's by default.

If Copona is installed on an Apache server running Mod_Rewrite, we automatically create the .htaccess file and turn on SEO URL's in the settings. It should still install fine on Nginx (tested a few days ago) or without mod_rewrite installed, it's just that additional steps will need to be taken to turn on SEO friendly URL's.

**Comment by prhost** [comment]
and why not create .htaccess by default?

**Comment by lucasjkr** [comment]
Nginx uses a different setup for rewrites, and recommends against .htaccess in general. 

We COULD create the htaccess by default, and just refer to the server type and modules installed when determining whether or not to automatically enable SEO URL's or not.

**Comment by prhost** [comment]
so let's leave a standard htaccess, it's just a place for maintenance, there's no risk of security if the server does not come to be apache.

**Comment by lucasjkr** [comment]
It works fine with or without the htaccess, the greater issue was turning on SEO URL's by default if we could determine that the server supports it. So, if someone installs on an Apache server with mod_rewrite enabled, SEO URL's are on by default. If they install on another server, they can still enable SEO URL's using the old method. That was my thought.

**Comment by prhost** [comment]
your thinking is right, just do not think it legal to create the htaccess file automatically, this is not common, but now as @janistravins approved, this discussion is no longer valid.

**Comment by lucasjkr** [comment]
We can still discuss or revisit it in the future.

I like how the config.php's are created automatically. Perhaps we just add a line to the step 2 screen to let the user know that htaccess will be created. 

And unfortunately, there are some OC users that just use the Admin interface, but get intimidated by FTP or command line access, so i just wanted to make it easier for them :)

**Comment by arnisjuraga** [comment]
Agree on both of you @prhost and @lucasjkr - we can still improve it in the future. There are still many issues can be raised depending on server versions etc. 
SEO url engine itself needs many changes, so this will be a topic in the future anyway.

**Pull request merged**
