### PR TITLE
Storage structure

### PR DESCRIPTION
**Pull request by prhost**
Keep `storage/` out of the `system/` folder.
Moving images cache into `storage/cache/`.

### CODE REVIEW

**Comment by ADDCreative** [comment]
You don't want to mix the image files that are remotely accessible with other files that absolutely must not be remotely accessible, such as the other cache files and the download, modifications and logs folders. You need an .htaccess with deny from all in storage, as this this was in the system folder above (with exceptions which I think are wrong). It will just get messy if some are files and folders are allowed and some deny.

By all means move the the storage for system, but don't mix with content. Maybe have a private storage and a public storage.

**Comment by ADDCreative** [comment]
It would also be useful to be able to serve the images (including cached) for a sub domain. It used to be easy to do this in older version, but DIR_IMAGE was removed at some point.

**Comment by prhost** [comment]
@ADDCreative understand its argument, the cache of the images are temporary, so they got inside the cache. The idea of separating in public and private is good. But it can not keep storage inside the system, the system folder is the core of the project, keeping a folder that is being written all the time is not reliable, separating, isola system so that no developer can move it, so we can create a system Update in the future without the developer running the risk of losing something. Same thing happens with the catalog folder, separating theme from it.

**Comment by prhost** [comment]
> It would also be useful to be able to serve the images (including cached) for a sub domain. It used to be easy to do this in older version, but DIR_IMAGE was removed at some point.

Can we put this in settings to facilitate this change, how does the url part work for only the subdomain support images?

**Comment by ADDCreative** [comment]
@prhost I agree with moving the storage from the system folder. However mixing information that must be secure (file cache of database queries) and public files (cached images) is wrong.

**Comment by prhost** [comment]
@ADDCreative 
Do you have any defense about moving storage into a system? Because the folders inside storage still remain secure, even if they are in the root.

The idea about public and private would be this:

***Public***
`storage/public/`
`storage/public/cache/image/`
...

***Private***
`storage/private/`
`storage/private/logs/`
`storage/private/cache/`
...

**Comment by ADDCreative** [comment]
>> It would also be useful to be able to serve the images (including cached) for a sub domain. It used to be easy to do this in older version, but DIR_IMAGE was removed at some point.

> Can we put this in settings to facilitate this change, how does the url part work for only the subdomain support images?

You used (< v1.5.5) to able to set a sub domain for images in the config.php files with the following.
define('HTTPS_IMAGE', 'https://images.example.com/image/');
define('DIR_IMAGE', '/home/imagesubdomin/public_html/image/');

model/tool/image.php used to return:
```return HTTPS_IMAGE . $new_image;``` instead of ```return HTTP_CATALOG . 'image/' . $new_image;```

Of course both the original images and the cached images both needed to be under DIR_IMAGE.

**Comment by ADDCreative** [comment]
> Public
storage/public/
storage/public/cache/image/
...
Private
storage/private/
storage/private/logs/
storage/private/cache/

That would work. You could then put a htacces in storage/private/ that denied access to all, without having to worry about allowing access to the public files.

**Comment by prhost** [comment]
@ADDCreative 
What do you think of creating the settings for this:

```
'image_cache_path' => 'storage/public/cache/image/',

'image_url' => 'subdomain.domain.com',
```

**Comment by ADDCreative** [comment]
Yes, it would be nice if that could be done.

**Comment by prhost** [comment]
I'm working on it. Thanks for the ideas.

**Comment by arnisjuraga** [comment]
IMHO is it safe, to relay only on .htaccess? What about Nginx and IIS servers?

**Comment by prhost** [comment]
@arnisjuraga Opencart and Copona not has nginx and IIS native support, apache like configuration scripts need to be made for them.

**Comment by prhost** [comment]
@ADDCreative @arnisjuraga 
I updated the merge request, now it has the configurations available in `config/general.php`:

```php
    /**
     * Image cache path
     *
     * The public path where the thumbs will be generated
     */
    'image_cache_path'      => PATH_CACHE_PUBLIC . 'image/',

    /**
     * Image base URL
     *
     * You can modify the base url of the images
     * Do not add protocol https or http
     */
    'image_base_url'        => DOMAIN_NAME . '/' . PATH_CACHE_PUBLIC . 'image/',
```

**Comment by arnisjuraga** [comment]
`storage/private/cache` folder is not created, if not exists

**Comment by arnisjuraga** [comment]
btw - for the best security, @ADDCreative isnt it good, to serve Document Root from subfolder? That would be nice, but unfortunately - me myself would not like it at the moment ... I think, again, the shared hostings requires more configuration and can be not so acceptable from users. 

In that case, all private files would not be accessible from outside, and supported solution for all webservers (just requires additional webserver config).

**Comment by prhost** [comment]
> `storage/private/cache` folder is not created, if not exists
fixed

**Comment by prhost** [comment]
>btw - for the best security, @ADDCreative isnt it good, to serve Document Root from subfolder? That would be nice, but unfortunately - me myself would not like it at the moment ... I think, again, the shared hostings requires more configuration and can be not so acceptable from users.

>In that case, all private files would not be accessible from outside, and supported solution for all webservers (just requires additional webserver config).

sorry, but I could not quite understand what I meant

**Comment by prhost** [comment]
conflicts 😢

**Comment by prhost** [comment]
thanks @arnisjuraga  and @JJKalnins

**Comment by ADDCreative** [comment]
Interestingly OpenCart 3.0.1.0 now pops up a message with the following.

> Important Security Notification! It is very imporant that you move the storage directory outside of the web directory (e.g. public_html or www).

And then gives the option to automatically move or instructions to manually move.

**Comment by arnisjuraga** [comment]
@ADDCreative couldn't  we just protect this folder and redirect by default if ` .env.` file or some maintenance file is/is not available. Something from @MartanLV  here https://github.com/copona/copona/issues/157#issuecomment-312994531

**Comment by ADDCreative** [comment]
@prhost Had to make a few changes to get things working.

One of the following should be should be cache_private.
https://github.com/copona/copona/blob/master/install/controller/install/step_2.php#L73-L74

You don't need the '/' between the config URL and $image, as '/' is on end in config.
https://github.com/copona/copona/blob/master/system/library/url.php#L138-L140

The following should be somthing like ```'image_base_url'        => rtrim(BASE_URL_CATALOG, '/') . '/' . PATH_CACHE_PUBLIC . 'image/',``` in case install in subfolder.
https://github.com/copona/copona/blob/master/config/general.php#L34

**Comment by prhost** [comment]
@ADDCreative thank you for your comments, I'm going to make these changes

**Comment by arnisjuraga** [comment]
@prhost pulled latest master on quite an old system, but seems, `/storage/private/upload` folder is not created automatically:

`<b>Warning</b>: move_uploaded_file(/public_html/storage/private/upload/logo2.pdf.hjk): failed to open stream: No such file or directory in <b>/public_html/catalog/controller/tool/upload.php</b> on line <b>67</b>`

**Comment by prhost** [comment]
https://github.com/copona/copona/commit/a28743e4e8c703fa6475fc03604b6e4abf454f8b

**Pull request merged**
