### PR TITLE
PHPMailer/Composer support

### PR DESCRIPTION
**Pull request by btafoya**
As requested, I have merged my PHPMailer changes as well as Composer support. The README will need to be changed to reflect a step to update the composer vendor directory.

composer update

https://getcomposer.org/doc/00-intro.md

### CODE REVIEW

**Comment by prhost** [comment]
Very good work 👏🏻  I had done the same thing, but at the time I implemented swiftmailer, but both libraries are very good.

**Comment by btafoya** [comment]
Thanks @prhost ... we should merge the two possibly so that the mailer can be a choice. They both have their strengths.

**Comment by arnisjuraga** [comment]
@btafoya - please, can you test it again? I have commented on pull request - there was problem with it.

**Comment by btafoya** [comment]
What was the issue you encountered?

**Comment by arnisjuraga** [comment]
~~~
PHP Fatal error:  Uncaught Exception: Error: Could not instantiate mail function.
~~~

https://github.com/copona/copona/pull/34

**Pull request merged**
