### PR TITLE
Revert "PHPMailer/Composer support"

### PR DESCRIPTION
**Pull request by arnisjuraga**
Reverts copona/copona#16

I did not succeed to use it on quite fresh Ubuntu server installation. Needs more tests:

~~~
PHP Fatal error:  Uncaught Exception: Error: Could not instantiate mail function.
~~~

### CODE REVIEW

**Comment by arnisjuraga** [comment]
#15 - needs testing. DId not work on fresh Copona / composer install

**Comment by btafoya** [comment]
This contribution was left out there for too long with other changes being made. I will have to update the fork in order to test and commit once again.

**Comment by btafoya** [comment]
phpMailer was unable to locate a sendmail compatible mailer. This is not a code error, the server used to test with was missing an MTA.

**Comment by arnisjuraga** [comment]
I did the tests on 2 different servers, and both have sendmail. Even if servers wouldn't have sendmail - mailer cannot end with Fatal error!

**Comment by btafoya** [comment]
I will see what I can do to mitigate the fatal error.

**Comment by arnisjuraga** [comment]
Yes, from what I see - you are using SMTP, which is no doubt the preferred method to use.
But we need to support mail() function as well. 

But try this solution, it could be the case: 

From what I have experienced, mail() will not work correctly on some PHP/OS versions, if you **specify sender**. I have used this one already in another project: http://stackoverflow.com/questions/1297084/phpmailer-error-could-not-instantiate-mail-function 

~~~php
$mail->AddAddress($address, "her name");
// should be changed to
$mail->AddAddress($address);
~~~

**Comment by btafoya** [comment]
Actually using SMTP is a configuration option just like the original mail
class which can be set in the admin.

**Comment by arnisjuraga** [comment]
Yes, I know. Just to be sure to make tests in both - smtp and mail()

**Pull request merged**
