### PR TITLE
Query Logging for MySQLi adapter

### PR DESCRIPTION
**Pull request by lucasjkr**
Enables MySQL query logging if MODE is defined and set to ‘debug’

Logs all queries to the system log directory, in a tab separated file, with the following fields:

Date/Time
Execution Time (ms)
Query SQL

### CODE REVIEW

**Comment by arnisjuraga** [comment]
Please, can you add sam notes in Readme.md for the instructions how to turn it on/off?

**Comment by prhost** [comment]
I do not think very correct to do this, and there is a constant DEBUG, could use the same instead of creating another constant, and how about installing and configuring that debugbar and let enabled or not through constant DEBUG?

**Comment by lucasjkr** [comment]
@prhost. I created a new constant because I wasn't certain what you were using DEBUG for. In fact, it took a few minutes to figure out why it was even being set somewhere already, as I had assumed config.sample.php would just be an example of what config.php should look like. 

Could we rework how DEBUG is set, wider range of IP Internal Addresses (I use the 10.x.x.x range) and/or setting allowing user to manually specify the IP Address? 

Also, how would you prefer to rework it? 

Correct me if I'm mistaken, but debugbar only extends PDO, not mysqli. Someone over at [Wordpress](https://github.com/maximebf/php-debugbar/issues/213) noted that as well (funny to now be pointing at Wordpress, after knocking them earlier).

Personally, I would LOVE to rework Copona to use PDO rather than mysqli, we could do a ton of cleanup of the queries if we were using prepared statements but that's further down the road.

**Last thought:**

I had also considering implementing this as a VQMOD, so you simply remove it from the vqmod directory when not needed. That might actually be more appropriate, now that I think about it.

Your thoughts?

**Comment by arnisjuraga** [comment]
- please, avoid use of vqmod anywhere. It can be done then and only if we are creating some module or changes, which must be done only locally, only for specific project and so on. Use of Vqmod is not useful at the moment, as we are changing source code and any search strings can change a lot.

- @prhost - Debug bar is a great idea! @lucasjkr as I understood, debugbar is meant as additional HTML somewhere, preferably, in the footer, which can be turned on, hidden, collapsable etc. during site debugging. This is a great method, how many systems use it. I have done small test of Kint time ago: https://github.com/arnisjuraga/kint-oc 
Now, by using composer, Kint can be implemented event easier (I still like my debug functions `pr()` and `prd()`, because they ar fast, simple and easy. But Kint gives, even more, flexibility). 

>  LOVE to rework Copona to use PDO

Call me old fashion, but there are something in a raw SQL selects. I still think that this is also one of the Copona (Opencart) differences from others.  We have already discussed it with @prhost  #31 - I am for PDO, ORM in the future. But they makes a system more complicated, harder to learn etc. 
It would be great to still allow usage of both - PDO un raw SQL. 
Rebuilding all SQLs to PDO also will take time. This is a matter of roadmap we have stared to discuss.

> Could we rework how DEBUG is set, wider range of IP Internal Addresses (I use the 10.x.x.x range) and/or setting allowing user to manually specify the IP Address?

Yes, it's done already. Just add additional IPs in `config.php` the same way you have in an example. Or any other check. It's simple way how to setup debug.

Your `10.x.x.x` should be added as:
~~~
strpos($ip, "10.") === 0
~~~
e.g.
~~~
if ($ip == '192.168.1.1' ||
	strpos($ip, "127.0.0.") === 0 ||
	strpos($ip, "192.168.0.") === 0 ||
      	strpos($ip, "10.") === 0 ||
	strpos($ip, "8.9.10") === 0) {
~~~

**Comment by arnisjuraga** [comment]
by the way - "debug" and "debug_sql" should be two different constants. While developing, I use "debug" on all the time, to be able to exec debug output functions. 
But I do not need to log all sql selects all the time - it's an overhead I think.

**Comment by lucasjkr** [comment]
I actually rewrote it as a VQMOD to check out the other site I'm working on. It might be best to revert that change and use the VQMOD instead - very doubtful that an end user would ever need to see the SQL Queries that are executing.

Thoughts?

**Comment by arnisjuraga** [comment]
At the moment, Copona is quite rough and developers used. As I am gainst VQmod anywhere, I vote for the implementation into core. 👍

**Comment by lucasjkr** [comment]
Yes - Debugbar looks interesting (first time I'd heard of it, honestly), but as I said, it appears to be PDO only.

Converting from mysqli to PDO shouldn't be terribly difficult, but we won't get benefits of things like prepared statements without doing a major rewrite. In fact, I just reinstalled copona using the mpdo driver, and it looks like it's working fine (to be expected - there's no worry extensions that worry about it).

This brings up a question, which might cause a lot more discussion.

**Why not drop mysqli_ altogether?**

"MySQL (PDO)" the default method (and only supported method, to start)? Are there any hosts that provide PHP5.6 without providing PDO?

We could then embark on re-crafting queries as prepared statements, without having to constantly check which driver is in use.

Biggest downside is probably one that we already face - I'm not sure about you guys, but I (currently) only have MySQL installed to test against. Later on, I could install PG or even MSSQL, but concentrating on one DB at a time would be best, probably.

**Also a note on ORM**

I like the idea of integrating Phinx to enable modules to manipulate the table structure in an abstract way, but I wouldn't be a fan of going full blown ORM - abstraction adds considerable overhead IMO.

**Pull request merged**
