### PR TITLE
Http and https awareness

### PR DESCRIPTION
**Pull request by lucasjkr**
This adds a huge, non-dismissible warning if the admin enters the /admin area without an SSL connection.

### CODE REVIEW

**Comment by arnisjuraga** [comment]
One small fix: now, if I set up 'https:' in `config.php` for both, HTTP_SERVER and HTTPS_SERVER - then I end up with perfectly running Copona on HTTPS without a problem. And I don't need to edit Admin settings for HTTPS, but - the warning message is still shown:

image

**Comment by lucasjkr** [comment]
I am not seeing that behavior?

**Comment by arnisjuraga** [comment]
This is an issue for `php-fpm` installation. Also Apache + `php-fpm`, there can be the problem. Current Copona can't "read", that request has been forwarded to php-fpm from HTTPS. 

E.g. fallback checks for compatibility [is_ssl() @Wordpress]. Of course, port 443 does not guarantee, that request is received from HTTPS, && it's encrypted, it's much more "[by convention]".

[is_ssl() @Wordpress]:https://github.com/WordPress/WordPress/blob/bdf608745086893f44b0abed7b44b233e35bacbb/wp-includes/load.php?ts=2#L967
[by convention]:http://stackoverflow.com/a/2886224/1720476

**Comment by arnisjuraga** [comment]
image

**Comment by prhost** [comment]
try change `startup.php` line 61 to `if ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || $_SERVER['SERVER_PORT'] == 443) {`

**Comment by arnisjuraga** [comment]
Just bumped into: https://github.com/opencart/opencart/pull/3784

**Pull request merged**
