### PR TITLE
Dynamic social media setting

### PR DESCRIPTION
**Pull request by hkaraoglu**
--> Refactored. All configs which has only if-else conditions (without else if condition) were moved to foreach loop.
--> Added config value for social media. (config_social_media).

admin/language->en-gb/setting/setting.php
--> Added language entries for social media section.

admin/view/javascript/jquery-ui.min.js
admin/view/template/common/header.tpl
--> jquery-ui library file was added to sort elements by dragging.

admin/view/template/setting/setting.tpl
--> A section was added  to configure social media pages.

catalog/controller/common/footer.php
catalog/themes/default/assets/css/stylesheet.css
catalog/themes/default/template/common/footer.tpl
--> HTML & CSS code was implemented to show social media icons on catalog side.

Screenshot : 
screen shot 2017-07-22 at 15 37 58

### CODE REVIEW

**Comment by hkaraoglu** [comment]
Screenshot : 
screen shot 2017-07-22 at 15 37 58

**Comment by prhost** [comment]
very nice

**Comment by prhost** [comment]
Test here and it's all right, but there was a lot of change in the project, you need to synchronize your fork with the project to test better.

**Comment by hkaraoglu** [comment]
I think I did it(synchronizing my fork) shortly before. Sorry for this. I used git a little. (Mostly, I used subversion). I will pay attention this in future.

**Pull request closed without merging**
