### PR TITLE
Extension manager

### PR DESCRIPTION
**Pull request by prhost**
***Test environment***
[http://51.15.48.17:4389/](http://51.15.48.17:4389/)

Created ExtensionManager to manage the extensions from now on.
It is still in development but the basic one that replaces glob has already been developed.
It creates a collection of all extensions and their files and keeps them at runtime to avoid fetching whenever you need them.

We need to document it after it's ready.

***Bonus:***

Refactoring the Template Engine, it is now defined which template engine adapter you want to use in `config/general.php`, by default you have both, php and twig, but you can develop your own adapter if you need to, just implement the Interface.

Now you can get instances registered in the Registry statically anywhere, just use the `\Registry::get('tax');` method.

Removed the damn Proxy and model callback (this is disgusting)
Remove auto unistall extensions when not found file

### CODE REVIEW

**Comment by arnisjuraga** [comment]
Pls check everybody. 
I will be ablo to do this only on next week. 

Please, post comments.

**Comment by arnisjuraga** [comment]
I have fixed conflicts, but I have few problems right after testing. Requires migration notes or automatic fixes:
- after login to admin and going to Settings, huge amount of 404 errors
image

- js error in admin under: `System > Settings > edit`
```
{error: {type: "RuntimeException",…}}
error
:
{type: "RuntimeException",…}
file
:
"/public_html/system/engine/Action.php"
line
:
60
message
:
"Controller /public_html/admin/controller/localisation/country/country.php not found."
type
:
"RuntimeException"
```

- in Homepage, even with Simplica theme, is error:
```
Unknown: Argument 2 passed to Copona\System\Engine\Action::execute() must be of the type array, string given, called in /public_html/system/engine/Loader.php on line 47 and defined in /public_html/system/engine/Action.php on line 39
English English 
```

**Comment by prhost** [comment]
I could not reproduce the error of the homepagedo simplica theme. The assets with 404 will be fixed in your branch asset, did not want to move to not give conflict.

I fixed the `RuntimeException` problem.

**Comment by arnisjuraga** [comment]
This one
```header.php:21```
~~~php
foreach ($analytics as $analytic) {
            if ($this->config->get($analytic['code'] . '_status')) {
                $data['analytics'][] = $this->load->controller('extension/analytics/' . $analytic['code'], 
                    $this->config->get($analytic['code'] . '_status'));
            }
        }
~~~
Generates error:

~~~
Unknown: Argument 2 passed to Copona\System\Engine\Action::execute() must be of the type array, 
string given, called in /public_html/system/engine/Loader.php on line 47 and defined in 
/public_html/system/engine/Action.php on line 31
~~~

**Comment by arnisjuraga** [comment]
Opening non-existing method e.g. `?route=nothing-here`, gives error:
image

**Comment by arnisjuraga** [comment]
check Slack:
- admin sales/order/info method "not found" 
- cannot create an order

**Comment by prhost** [comment]
I fixed the problems, less of the `checkout/guest`, this is problem in the checkout, Method is missing, `load->controller` now triggers exception, it is not related to this merge request.

**Comment by arnisjuraga** [comment]
Great merge! Please, there still can be issues on this, so everyone - please test and report!

**Comment by arnisjuraga** [comment]
This is sick ....
I just played with an Opencart shop, trying to implement some changes from Copona ... 
I noticed, that `__construct` method from  `model/catalog/category` was called 4x times on every page load...

 That was not good, because Categories uses a lot of RAM. All page In total - used ~77 MB of RAM for every page load.

... digging deeper, I narrowed it down, that Opencart loader uses this nasty `Proxy()` class, with `callback` method ... which generated a lot of duplicate model calls.  Removing `Proxy` from `loader.php` ... - and the RAM amount dropped down to 25MB per script ....

this is just ....uhhhhh... Opencart performance! :) 
Thanks @prhost for this commit! :)

**Comment by prhost** [comment]
I'm trying this category problem on a recent project, had to implement some caches on their request, and clear the cache automatically in panel category management.

**Pull request merged**
