### PR TITLE
Enable/Disable part numbers by type

### PR DESCRIPTION
**Pull request by lucasjkr**
This is a change to the admin.

Currently, when editing a product, you get many part number choices (SKU, UPC, EAN, JAN, ISBN, MPN). This allows you to disable the ones you don’t actually need.

You do so in Settings -> Your Store -> Option tab.

To be resolved: If you’ve entered a certain type of part number (ISBN for instance), then disable that type of part number, when you next edit a product and save it, it will delete the part number.

Perhaps we choose to retain those by adding hidden fields to the form? What are your thoughts?

### CODE REVIEW

**Comment by arnisjuraga** [comment]
> Perhaps we choose to retain those by adding hidden fields to the form? What are your thoughts?

Yes, unfortunately, I think - this is very important...
I have used these custom fields for "temporary" or "technical" information. E.g. - if we import some .XML product files int the system, we need to store "original ID", or some other information, which is not planned to be editable in the admin for users. 

And for that, we use some of these fields.

If we disable them in admin, for better UX, then upon first product edit in admin, this information will be removed. 

The better solution would be, just to NOT update, NOT change them.

One of the solutions:
1) just use them as CSS "display: none", - so input fields are still in admin. It can make some debugging harder because you can't see something in admin, which really exists there.
2) or - we just remove those fields from the SQL update, if they are disabled in admin. This requires more changes in your solution, more "check" in products model.
3) If disabled in store settings, move those un-needed fields to "Advanced" tab in product Edit, where are all fields, which are not needed-used by an ordinary user. But this involves much more dev into .tpl files, which is messy...

Can anyone think about an easier solution?

**Comment by lucasjkr** [comment]
I should have updated my comment on this pull request (that was originally made last night for me). 

My final commit on this pull request (made this morning for me) already solved for that by adding hidden fields to /admin/view/template/catalog/product_form.tpl).

If a part number has been disabled, it's still present in the product form as a hidden field, and therefore the values continue to be preserved after additional edits are made.

**Comment by lucasjkr** [comment]
https://github.com/copona/copona/pull/124/commits/55ab630fdc7310b8a24a531f64a72c5934411876

**Comment by arnisjuraga** [comment]
Good!

**Pull request merged**
