### PR TITLE
Installation fixes

### PR DESCRIPTION
**Pull request by lucasjkr**
Server hostname detection changed for compatibility with Nginx.

For Apache servers running with mod_rewrite, .htaccess is only created
if it doesn’t exist already, otherwise existing .htaccess is preserved.

SEO URL’s are only turned on if .htaccess was created (rather than
preserved)

### CODE REVIEW

**Comment by lucasjkr** [comment]
This should address issues raised by @arnisjuraga  and ADDCreative (I can't tag the later)

**Comment by arnisjuraga** [comment]
Is there anything we can integrate from here? Default Nginx .conf file? https://github.com/opencart/opencart/pull/5365

**Comment by prhost** [comment]
Also does not find interesting the installer extension, opencart is not modular, and this may have fail and cause to lose codes, than actually facilitate the use.
Twig is very good and important, but the way they implemented it, it would never do so, I once sent to opencart, an implementation of twig, which left the modular template hander, but he declined.

Has some interesting features like theme editor, dynamic menu, dynamic dashboard, but I think we would do better than it was done in opencart hehe, but copying these features would be faster, just by adapting them.

The opencart theme of both catalog and admin, which was converted to twig, would save us a lot of work as well, we can copy whatever is compatible with our version.

**Comment by prhost** [comment]
sory, i wrote in the wrong place

**Pull request merged**
