### PR TITLE
--> Dynamic social media 

### PR DESCRIPTION
**Pull request by hkaraoglu**
Refactored. All configs which has only if-else conditions (without else if condition) were moved to foreach loop.

--> Added config value for social media. (config_social_media).

admin/language->en-gb/setting/setting.php
--> Added language entries for social media section.

admin/view/javascript/jquery-ui.min.js
admin/view/template/common/header.tpl
--> jquery-ui library file was added to sort elements by dragging.

admin/view/template/setting/setting.tpl
--> A section was added to configure social media pages.

catalog/controller/common/footer.php
catalog/themes/default/assets/css/stylesheet.css
catalog/themes/default/template/common/footer.tpl
--> HTML & CSS code was implemented to show social media icons on catalog side.

### CODE REVIEW

**Comment by arnisjuraga** [comment]
1. How does social media icons are created, added? They are empty on my test site, and did not found the way, how to add them.
 - shouldn't it be better to use some font icons by default? E.g. these are available by default in Font Awesome css:
image

~~~
<i class="fa fa-facebook"></i>
<i class="fa fa-google"></i>
<i class="fa fa-twitter"></i>
~~~

2. if I add empty social icons, they still appears in html, should be either not saved at all (if empty) or not outputed at all (if empty)
image

3. can you replace `jquery.gui` with only `Sortable` package? 
http://jqueryui.com/download/#!version=1.12.1&components=101000000100000010000000010000000000000000000000

**Comment by hkaraoglu** [comment]
Ok. I will pay attention for this.

**Comment by arnisjuraga** [comment]
If you don't mind changing this, then we can wait for update and then merge?

**Comment by hkaraoglu** [comment]
Yes, wait please. I'm gonna update my code by your advices.

**Comment by arnisjuraga** [comment]
@hkaraoglu is it ready?

**Pull request merged**
